# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jekyll and Twitter Bootstrap 4.x
email: david.jacquel@gmail.com
description: Using Jekyll and Twitter Bootstrap 4.x
baseurl: "/jekyll-twb-4.x"
url: "http://pygmeeweb.com"
twitter_username: djacquel
github_username:  djacquel

# Build settings
markdown: kramdown

sass:
  # loading path from site root
  # default to _sass
  sass_dir: node_modules/bootstrap/scss

  # style : nested (default), compact, compressed, expanded
  #         :nested, :compact, :compressed, :expanded also works
  # see http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  # on a typical twitter bootstrap stats are :
  # nested 138,7kB, compact 129,1kB, expanded 135,9 kB, compressed 122,4 kB
  style: compressed

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
